# By Jonathan Christen
url_replace_bible_number = "$bible_number$"
url_replace_bible        = "$version$"
url_replace_book         = "$book$"
url_replace_chapter      = "$chapter$"
url_base    = 'https://www.bible.com/es/bible/$bible_number$/$book$.$chapter$.$version$'
chapter_language = {'english': 'Chapter', 'spanish': 'Capitulo', 'Arabic': 'الفصل'}
books_table_spanish = [
        ["Génesis",          "GEN"],
        ["Éxodo",            "EXO"],
        ["Levítico",         "LEV"],
        ["Números",          "NUM"],
        ["Deuteronomio",     "DEU"],
        ["Josué",            "JOS"],
        ["Jueces",           "JDG"],
        ["Rut",              "RUT"],
        ["Samuel 1",         "1SA"],
        ["Samuel 2",         "2SA"],
        ["Reyes 1",          "1KI"],
        ["Reyes 2",          "2KI"],
        ["Crónicas 1",       "1CH"],
        ["Crónicas 2",       "2CH"],
        ["Esdras",           "EZR"],
        ["Nehemías",         "NEH"],
        ["Ester",            "EST"],
        ["Job",              "JOB"],
        ["Salmo",            "PSA"],
        ["Proverbios",       "PRO"],
        ["Eclesiastés",      "ECC"],
        ["Cantares",         "SNG"],
        ["Isaías",           "ISA"],
        ["Jeremías",         "JER"],
        ["Lamentaciones",    "LAM"],
        ["Ezequiel",         "EZK"],
        ["Daniel",           "DAN"],
        ["Oseas",            "HOS"],
        ["Joel",             "JOL"],
        ["Amós",             "AMO"],
        ["Abdías",           "OBA"],
        ["Jonás",            "JON"],
        ["Miqueas",          "MIC"],
        ["Nahúm",            "NAM"],
        ["Habacuc",          "HAB"],
        ["Sofonías",         "ZEP"],
        ["Hageo",            "HAG"],
        ["Zacarías",         "ZEC"],
        ["Malaquías",        "MAL"],
        ["Mateo",            "MAT"],
        ["Marcos",           "MRK"],
        ["Lucas",            "LUK"],
        ["Juan",             "JHN"],
        ["Hechos",           "ACT"],
        ["Romanos",          "ROM"],
        ["Corintios 1",      "1CO"],
        ["Corintios 2",      "2CO"],
        ["Gálatas",          "GAL"],
        ["Efesios",          "EPH"],
        ["Filipenses",       "PHP"],
        ["Colosenses",       "COL"],
        ["Tesalonicenses 1", "1TH"],
        ["Tesalonicenses 2", "2TH"],
        ["Timoteo 1",        "1TI"],
        ["Timoteo 2",        "2TI"],
        ["Tito",             "TIT"],
        ["Filemón",          "PHM"],
        ["Hebreos",          "HEB"],
        ["Santiago",         "JAS"],
        ["Pedro 1",          "1PE"],
        ["Pedro 2",          "2PE"],
        ["Juan 1",           "1JN"],
        ["Juan 2",           "2JN"],
        ["Juan 3",           "3JN"],
        ["Judas",            "JUD"],
        ["Apocalipsis",      "REV"]
]
books_table_english = [
        ["Genesis",          "GEN"],
        ["Exodus",           "EXO"],
        ["Leviticus",        "LEV"],
        ["Numbers",          "NUM"],
        ["Deuteronomy",      "DEU"],
        ["Joshua",           "JOS"],
        ["Judges",           "JDG"],
        ["Ruth",             "RUT"],
        ["Samuel 1",         "1SA"],
        ["Samuel 2",         "2SA"],
        ["Kings 1",          "1KI"],
        ["Kings 2",          "2KI"],
        ["Chronicles 1",     "1CH"],
        ["Chronicles 2",     "2CH"],
        ["Ezra",             "EZR"],
        ["Nehemiah",         "NEH"],
        ["Esther",           "EST"],
        ["Job",              "JOB"],
        ["Psalms",           "PSA"],
        ["Proverbs",         "PRO"],
        ["Ecclesiastes",     "ECC"],
        ["Song of Solomon",  "SNG"],
        ["Isaiah",           "ISA"],
        ["Jeremiah",         "JER"],
        ["Lamentaciones",    "LAM"],
        ["Ezekiel",          "EZK"],
        ["Daniel",           "DAN"],
        ["Hosea",            "HOS"],
        ["Joel",             "JOL"],
        ["Amos",             "AMO"],
        ["Obadiah",          "OBA"],
        ["Jonah",            "JON"],
        ["Micah",            "MIC"],
        ["Nahum",            "NAM"],
        ["Habakkuk",         "HAB"],
        ["Zephaniah",        "ZEP"],
        ["Haggai",           "HAG"],
        ["Zechariah",        "ZEC"],
        ["Malachi",          "MAL"],
        ["Matthew",          "MAT"],
        ["Mark",             "MRK"],
        ["Luke",             "LUK"],
        ["John",             "JHN"],
        ["Acts",             "ACT"],
        ["Romans",           "ROM"],
        ["Corinthians 1",    "1CO"],
        ["Corinthians 2",    "2CO"],
        ["Galatians",        "GAL"],
        ["Ephesians",        "EPH"],
        ["Philippians",      "PHP"],
        ["Colossians",       "COL"],
        ["Thessalonians 1",  "1TH"],
        ["Thessalonians 2",  "2TH"],
        ["Timothy 1",        "1TI"],
        ["Timothy 2",        "2TI"],
        ["Titus",            "TIT"],
        ["Philemon",         "PHM"],
        ["Hebrews",          "HEB"],
        ["James",            "JAS"],
        ["Peter 1",          "1PE"],
        ["Peter 2",          "2PE"],
        ["John 1",           "1JN"],
        ["John 2",           "2JN"],
        ["John 3",           "3JN"],
        ["Jude",             "JUD"],
        ["Revelation",       "REV"]
]